// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260416210523_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.15");

            modelBuilder.Entity("backend.Models.Guest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Guests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "vd",
                            Name = "Виктория и Дмитрий"
                        },
                        new
                        {
                            Id = 2,
                            Code = "aa",
                            Name = "Анастасия и Антон"
                        },
                        new
                        {
                            Id = 3,
                            Code = "yana",
                            Name = "Яна"
                        });
                });

            modelBuilder.Entity("backend.Models.GuestPerson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("Attending")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DietaryRestrictions")
                        .HasColumnType("TEXT");

                    b.Property<int>("GuestId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GuestId");

                    b.ToTable("GuestPersons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GuestId = 1,
                            Name = "Виктория"
                        },
                        new
                        {
                            Id = 2,
                            GuestId = 1,
                            Name = "Дмитрий"
                        },
                        new
                        {
                            Id = 3,
                            GuestId = 2,
                            Name = "Анастасия"
                        },
                        new
                        {
                            Id = 4,
                            GuestId = 2,
                            Name = "Антон"
                        },
                        new
                        {
                            Id = 5,
                            GuestId = 3,
                            Name = "Яна"
                        });
                });

            modelBuilder.Entity("backend.Models.Rsvp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GuestId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GuestId")
                        .IsUnique();

                    b.ToTable("Rsvps");
                });

            modelBuilder.Entity("backend.Models.GuestPerson", b =>
                {
                    b.HasOne("backend.Models.Guest", "Guest")
                        .WithMany("Persons")
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guest");
                });

            modelBuilder.Entity("backend.Models.Rsvp", b =>
                {
                    b.HasOne("backend.Models.Guest", "Guest")
                        .WithOne("Rsvp")
                        .HasForeignKey("backend.Models.Rsvp", "GuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guest");
                });

            modelBuilder.Entity("backend.Models.Guest", b =>
                {
                    b.Navigation("Persons");

                    b.Navigation("Rsvp");
                });
#pragma warning restore 612, 618
        }
    }
}
